ALTER TABLE "Campaign"
ADD COLUMN IF NOT EXISTS "enableMessageIdentity" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "aiDisplayName" TEXT,
ADD COLUMN IF NOT EXISTS "enableAiPrefix" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "enableAgentPrefix" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "agentNameMode" TEXT NOT NULL DEFAULT 'FIRST_NAME';
