ALTER TABLE "CampaignDistributionMember"
ADD COLUMN IF NOT EXISTS "shiftStartHour" INTEGER,
ADD COLUMN IF NOT EXISTS "shiftEndHour" INTEGER,
ADD COLUMN IF NOT EXISTS "shiftDays" INTEGER[],
ADD COLUMN IF NOT EXISTS "timezone" TEXT;